# GoatedFactions Configuration (GFactions)

# Power System Settings
power:
  initial: 100             # Power a new faction (owner) starts with
  per_member_bonus: 100    # Max power increase per member (including owner)
  # Power Regeneration (per hour)
  regeneration:
    offline_amount_per_hour: 2
    online_amount_per_hour: 5
  # Power Loss on Death by Enemy
  loss_on_death:
    member: 24
    admin_owner: 50 # For Admins and Owners
  # Power Decay (after prolonged inactivity)
  decay:
    enabled: true
    days_inactive_before_decay_starts: 30 # Days a faction must be inactive (no member logins)
    decay_amount_per_day: 5               # Power lost per day once decay starts
    check_interval_hours: 24              # How often to check for and apply decay (e.g., every 24 hours)
  cost:
    claim_chunk: 5
    overclaim_chunk: 20       # Default cost for overclaiming
    declare_enemy: 10
    declare_neutral: 10
    send_ally_request: 10
    promote_member: 2
    trust_player: 1
    create_outpost: 50        # Cost to create an outpost

# Cooldowns & Expirations
cooldowns:
  enemy_neutral_declaration_hours: 24 # Cooldown before an enemy can be made neutral
  member_invite_expiration_minutes: 5
  ally_request_expiration_minutes: 5

# Teleportation Settings
teleport:
  warmup_seconds: 5

# Title Display Settings (when entering claims)
titles:
  fade_in_ticks: 5
  stay_ticks: 30
  fade_out_ticks: 5
  display_cooldown_seconds: 1 # Reduced to allow quicker overwrite for new areas

# Dynmap Integration Settings
dynmap:
  enabled: true
  markerset_label: "Faction Claims"
  style:
    stroke_weight: 2          # Weight of the claim border line
    stroke_opacity: 0.80      # Opacity of the border line
    stroke_color: "0x000000"  # Color of border line (black, hex string), used for merged polygons
    fill_opacity: 0.35        # Opacity of the claim fill
    default_claim_color: "0x00FF00" # Green (as hex string) - Used for player's own faction fill
    enemy_claim_color: "0xFF0000"   # Red - Used for enemy faction fill
    ally_claim_color: "0x00FFFF"    # Cyan - Used for ally faction fill
    neutral_claim_color: "0xFFFF00" # Yellow - Used for neutral faction fill (if not self, ally, or enemy)

# Faction Settings
faction_details:
  name_min_length: 3
  name_max_length: 16
  name_regex: "^[a-zA-Z0-9_]+$" # Allows letters, numbers, underscore
  # Chat Settings
  chat:
    faction_chat_enabled: true
    ally_chat_enabled: true
    faction_chat_format: "&8[&2{RANK}&8][&a{FACTION_NAME}&8] &f{PLAYER_NAME}: &e{MESSAGE}" # {RANK} added
    ally_chat_format: "&8[&6ALLY&8][&a{FACTION_NAME}&8] &f{PLAYER_NAME}: &e{MESSAGE}"
    public_chat_prefix_format: "&7[{FACTION_NAME}&7] &r" # Prefix for public chat
  # Feature Toggles
  enemy_system_enabled: true
  vault_system_enabled: true
  outpost_system_enabled: true
  pvp_protection_system_enabled: false # NEW: Master toggle for the PvP Protection feature
  max_outposts: 1                 # Maximum number of outposts a faction can have
  # /f info (or /f who) Screen Display Toggles
  who_screen_display:
    show_owner: true
    show_power: true
    show_claims: true
    show_pvp_status: true
    show_home_location: false # Disabled by default as requested
    show_leadership_list: true
    show_members_list: true
    show_associates_list: true
    show_allies_list: true
    show_enemies_list: true
    show_outposts: true


# Claiming Restrictions
claiming:
  # Claim Limits
  base_claim_limit: 25            # Initial number of claims a new faction gets
  claims_per_member_bonus: 10     # Additional claims per member (including owner)
  # Spawn Protection
  prevent_claim_near_spawn: true
  spawn_protection_radius_chunks: 3 # Radius in CHUNKS around server spawn where claiming is prevented
  # Dimension Claiming
  allow_nether_claiming: false
  allow_end_claiming: false
  # Auto Claim
  autoclaim_enabled: true
  # Claim Fill
  claimfill_enabled: true
  # disallowed_claim_worlds: [] # Example: ["event_world", "minigame_world_nether"]

# Messages (can be expanded)
messages:
  entering_wilderness: "&7Now entering Wilderness"
  entering_faction_territory: "&7Now entering {FACTION_RELATION_COLOR}{FACTION_NAME}" # {FACTION_RELATION_COLOR} will be replaced dynamically
  faction_guide:
    - "&6--- Faction Guide ---"
    - "&eCreating a Faction: &fUse /f create <name>"
    - "&ePower: &fPower is crucial for claiming and maintaining land."
    - "&f - Factions gain max power per member."
    - "&f - Power regenerates over time, faster if members are online."
    - "&f - Losing all power makes your claims vulnerable!"
    - "&f - Dying to enemies can cause power loss."
    - "&eClaims: &fUse /f claim to expand your territory."
    - "&eMore help: &fUse /f help for a full command list."
# --- Data Storage - Do Not Manually Edit Below This Line ---
factions: {}
pendingAllyRequests: {}
pendingMemberInvites: {}
faction_last_online: {} # Stores last online timestamp for factions (for power decay)