name: GFactions
version: ${project.version}
main: gg.goatedcraft.gfactions.GFactionsPlugin
api-version: '1.21'
author: GoatedCraft
description: A feature-rich faction plugin for Purpur servers.
softdepend: [dynmap, Vault, PlaceholderAPI]

commands:
  faction:
    aliases: [f, fac]
    description: Main command for factions.
    usage: "/<command> help for subcommands"
  factionadmin:
    aliases: [fa, facadmin]
    description: Admin commands for GoatedFactions.
    usage: /<command> <subcommand> [args]
    permission: goatedfactions.admin

permissions:
  goatedfactions.use:
    description: Allows basic use of faction commands.
    default: true
  goatedfactions.admin:
    description: Allows admin control over factions and use of /fa commands.
    default: op
  goatedfactions.admin.bypass:
    description: Allows bypassing faction build/interact protection.
    default: op
  goatedfactions.admin.bypassspawnprotection:
    description: Allows claiming and creating factions near server spawn.
    default: op
  goatedfactions.admin.spy:
    description: Allows seeing faction-only chat messages.
    default: op
  goatedfactions.admin.allyspy:
    description: Allows seeing ally-only chat messages.
    default: op
